### ISSUE TITLE
Error compiling on Raspian 10

### ISSUE THREAD

**Issue by ej0rge** [relarn/relarn#1]
Just tried to build relarn on my pi 4 running raspian 10 desktop. 

Bombed out with these errors:

`show.c: In function ‘inv_line’:
show.c:44:48: error: ‘ (’ directive output may be truncated writing 2 bytes into a region of size between 1 and 260 [-Werror=format-truncation=]
         snprintf(result, sizeof(result), "%-40s (%d GP)", buffer, price);
                                                ^~
show.c:44:9: note: ‘snprintf’ output between 48 and 317 bytes into a destination of size 300
         snprintf(result, sizeof(result), "%-40s (%d GP)", buffer, price);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [Makefile:57: show.o] Error 1
`

Additionally, there's a missing = on line 44 of config.mk

Other than that, thanks much for the code refresh. I'm toying with the idea of a public art project that involves setting up an old vt220 and a pi zero as a coin operated roguelike video game. I didn't have any issues compiling and running on ubuntu/bionic on an amd64 system.

**Comment by suetanvil** [comment]
You can work around this by editing src/Makefile and removing `-Werror` on line 24 (the `CFLAGS=` line).

The problem is that as gcc gets smarter, it comes up with more warnings which breaks the build because I treat them as errors.  I'll probably have to come up with a clean way to make this property optional and off by default.

Also: apologies for taking so long to get back to you.  I'm taking a break from ReLarn at the moment and haven't been checking the site.

**Comment by suetanvil** [comment]
I seem to have fixed the problem and confirmed that it builds on Raspbian 10.3 as well as a couple of other platforms. You will now have to put the option 'RELEASE=yes' after the make command, however.  See README.md for details.

**Comment by ej0rge** [comment]
Thanks!
